### ISSUE TITLE
Build error related to missing asio package

### ISSUE THREAD

**Issue by kenembanisi** [PARC-Robotics/PARC-Engineers-League#1]
I'm not sure if this is a complete solution, but I was able to build after I installed `libasio-dev`:

`sudo apt install libasio-dev`

**Comment by siksal** [comment]
@kenembanisi 
I'm not sure about this because I did not have to install it before running. However, there is a plugin necessary for the GPS sensor:
`sudo apt-get install ros-noetic-hector-gazebo-plugins`.

From what I read [here](https://packages.debian.org/sid/libasio-dev), the `libasio-dev` is asio is a cross-platform C++ library for network programming that provides developers with a consistent asynchronous I/O model using a modern C++ approach.
